FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool autopoint bison flex

COPY . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/src/.libs
